### ISSUE TITLE
docker域名解析异常

### ISSUE THREAD

**Issue by cncherisher** [SuperNG6/docker-bilibili-helper#28]
运行时发生UnknownHostException异常
```
2021-06-19 09:50:26 INFO  : ------登录检查开始------
java.net.UnknownHostException: api.bilibili.com: Temporary failure in name resolution
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at top.misec.utils.HttpUtil.doGet(HttpUtil.java:134)
	at top.misec.utils.HttpUtil.doGet(HttpUtil.java:106)
	at top.misec.task.UserCheck.run(UserCheck.java:28)
	at top.misec.task.DailyTask.doDailyTask(DailyTask.java:63)
	at top.misec.BiliMain.main(BiliMain.java:63)
用户信息请求失败，如果是412错误，请在config.json中更换UA，412问题仅影响用户信息确认，不影响任务
2021-06-19 09:50:38 INFO  : ------登录检查结束------

2021-06-19 09:50:38 INFO  : -----随机暂停1626ms-----

2021-06-19 09:50:40 INFO  : ------硬币情况统计开始------
java.net.UnknownHostException: api.bilibili.com
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at top.misec.utils.HttpUtil.doGet(HttpUtil.java:134)
	at top.misec.utils.HttpUtil.doGet(HttpUtil.java:106)
	at top.misec.task.CoinLogs.run(CoinLogs.java:17)
	at top.misec.task.DailyTask.doDailyTask(DailyTask.java:63)
	at top.misec.BiliMain.main(BiliMain.java:63)
本次执行推送日志到Telegram

java.net.UnknownHostException: api.telegram.org: Temporary failure in name resolution
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at top.misec.utils.HttpUtil.doPost(HttpUtil.java:94)
	at top.misec.utils.HttpUtil.doPost(HttpUtil.java:54)
	at top.misec.push.AbstractPush.doPush(AbstractPush.java:24)
	at top.misec.push.PushHelper.push(PushHelper.java:32)
	at top.misec.task.ServerPush.doServerPush(ServerPush.java:52)
	at top.misec.task.DailyTask.doDailyTask(DailyTask.java:72)
	at top.misec.BiliMain.main(BiliMain.java:63)

java.net.UnknownHostException: api.telegram.org: Temporary failure in name resolution
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at top.misec.utils.HttpUtil.doPost(HttpUtil.java:94)
	at top.misec.utils.HttpUtil.doPost(HttpUtil.java:54)
	at top.misec.push.AbstractPush.doPush(AbstractPush.java:24)
	at top.misec.push.PushHelper.push(PushHelper.java:32)
	at top.misec.task.ServerPush.doServerPush(ServerPush.java:52)
	at top.misec.task.DailyTask.doDailyTask(DailyTask.java:72)
	at top.misec.BiliMain.main(BiliMain.java:63)
任务状态推送失败，开始重试

java.net.UnknownHostException: api.telegram.org
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at top.misec.utils.HttpUtil.doPost(HttpUtil.java:94)
	at top.misec.utils.HttpUtil.doPost(HttpUtil.java:54)
	at top.misec.push.AbstractPush.retryPush(AbstractPush.java:42)
	at top.misec.push.AbstractPush.doPush(AbstractPush.java:31)
	at top.misec.push.PushHelper.push(PushHelper.java:32)
	at top.misec.task.ServerPush.doServerPush(ServerPush.java:52)
	at top.misec.task.DailyTask.doDailyTask(DailyTask.java:72)
	at top.misec.BiliMain.main(BiliMain.java:63)

java.net.UnknownHostException: api.telegram.org
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at top.misec.utils.HttpUtil.doPost(HttpUtil.java:94)
	at top.misec.utils.HttpUtil.doPost(HttpUtil.java:54)
	at top.misec.push.AbstractPush.retryPush(AbstractPush.java:42)
	at top.misec.push.AbstractPush.doPush(AbstractPush.java:31)
	at top.misec.push.PushHelper.push(PushHelper.java:32)
	at top.misec.task.ServerPush.doServerPush(ServerPush.java:52)
	at top.misec.task.DailyTask.doDailyTask(DailyTask.java:72)
	at top.misec.BiliMain.main(BiliMain.java:63)
任务状态推送失败，开始第1次重试

java.net.UnknownHostException: api.telegram.org
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at top.misec.utils.HttpUtil.doPost(HttpUtil.java:94)
	at top.misec.utils.HttpUtil.doPost(HttpUtil.java:54)
	at top.misec.push.AbstractPush.retryPush(AbstractPush.java:42)
	at top.misec.push.AbstractPush.doPush(AbstractPush.java:31)
	at top.misec.push.PushHelper.push(PushHelper.java:32)
	at top.misec.task.ServerPush.doServerPush(ServerPush.java:52)
	at top.misec.task.DailyTask.doDailyTask(DailyTask.java:72)
	at top.misec.BiliMain.main(BiliMain.java:63)

java.net.UnknownHostException: api.telegram.org
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at top.misec.utils.HttpUtil.doPost(HttpUtil.java:94)
	at top.misec.utils.HttpUtil.doPost(HttpUtil.java:54)
	at top.misec.push.AbstractPush.retryPush(AbstractPush.java:42)
	at top.misec.push.AbstractPush.doPush(AbstractPush.java:31)
	at top.misec.push.PushHelper.push(PushHelper.java:32)
	at top.misec.task.ServerPush.doServerPush(ServerPush.java:52)
	at top.misec.task.DailyTask.doDailyTask(DailyTask.java:72)
	at top.misec.BiliMain.main(BiliMain.java:63)
任务状态推送失败，开始第2次重试

java.net.UnknownHostException: api.telegram.org
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at top.misec.utils.HttpUtil.doPost(HttpUtil.java:94)
	at top.misec.utils.HttpUtil.doPost(HttpUtil.java:54)
	at top.misec.push.AbstractPush.retryPush(AbstractPush.java:42)
	at top.misec.push.AbstractPush.doPush(AbstractPush.java:31)
	at top.misec.push.PushHelper.push(PushHelper.java:32)
	at top.misec.task.ServerPush.doServerPush(ServerPush.java:52)
	at top.misec.task.DailyTask.doDailyTask(DailyTask.java:72)
	at top.misec.BiliMain.main(BiliMain.java:63)

java.net.UnknownHostException: api.telegram.org
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at top.misec.utils.HttpUtil.doPost(HttpUtil.java:94)
	at top.misec.utils.HttpUtil.doPost(HttpUtil.java:54)
	at top.misec.push.AbstractPush.retryPush(AbstractPush.java:42)
	at top.misec.push.AbstractPush.doPush(AbstractPush.java:31)
	at top.misec.push.PushHelper.push(PushHelper.java:32)
	at top.misec.task.ServerPush.doServerPush(ServerPush.java:52)
	at top.misec.task.DailyTask.doDailyTask(DailyTask.java:72)
	at top.misec.BiliMain.main(BiliMain.java:63)
任务状态推送失败，开始第3次重试
Exception in thread "main" java.lang.NullPointerException
	at top.misec.task.CoinLogs.run(CoinLogs.java:18)
	at top.misec.task.DailyTask.doDailyTask(DailyTask.java:63)
	at top.misec.BiliMain.main(BiliMain.java:63)
==================2021/06/19 09:50:50==================
==========今天已签到完毕，下次签到时间为1d后===========
```
docker-compose文件
```
version: "3"
services:
  bilibili-helper:
    image: superng6/bilibili-helper:1.4.5
    container_name: bilibili-helper
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - TASK=1d
      - DEDEUSERID=xxx
      - SESSDATA=xxx
      - BILI_JCT=xxx
      - TELEGRAMBOTTOKEN=xxx
      - TELEGRAMCHATID=xxx
    volumes:
      - ./config:/config
    restart: always
```

已经尝试切换1.4.3/1,4,5/latest均有该问题
vps位于美国，dns为1.1.1.1

**Comment by cncherisher** [comment]
重启下vps就好了
