### ISSUE TITLE
运行报错「com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException」

### ISSUE THREAD

**Issue by yxmg** [SuperNG6/docker-bilibili-helper#29]
前两天开始报错，日志如下
```
2021-06-25 14:53:04 INFO  : ------银瓜子换硬币开始------
bilibili-helper    | com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
bilibili-helper    | 	at com.google.gson.JsonParser.parse(JsonParser.java:65)
bilibili-helper    | 	at com.google.gson.JsonParser.parse(JsonParser.java:45)
bilibili-helper    | 	at top.misec.utils.HttpUtil.processResult(HttpUtil.java:156)
bilibili-helper    | 	at top.misec.utils.HttpUtil.doGet(HttpUtil.java:136)
bilibili-helper    | 	at top.misec.utils.HttpUtil.doGet(HttpUtil.java:107)
bilibili-helper    | 	at top.misec.task.Silver2coin.run(Silver2coin.java:25)
bilibili-helper    | 	at top.misec.task.DailyTask.doDailyTask(DailyTask.java:65)
bilibili-helper    | 	at top.misec.BiliMain.main(BiliMain.java:65)
bilibili-helper    | Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
bilibili-helper    | 	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
bilibili-helper    | 	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1409)
bilibili-helper    | 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
bilibili-helper    | 	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
bilibili-helper    | 	at com.google.gson.JsonParser.parse(JsonParser.java:60)
```

**Comment by SuperNG6** [comment]
今天更新了，试一下新版。
先删除老的配置文件

**Comment by yxmg** [comment]
换成官方镜像源更新镜像就可以了 Thks
