### ISSUE TITLE
这是怎么回事？

### ISSUE THREAD

**Issue by pytwj** [SuperNG6/docker-bilibili-helper#36]
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[BILIBILI-HELPER.jar:?]
	at top.misec.utils.HttpUtil.doPost(HttpUtil.java:98) [BILIBILI-HELPER.jar:?]
	at top.misec.utils.HttpUtil.doPost(HttpUtil.java:58) [BILIBILI-HELPER.jar:?]
	at top.misec.push.AbstractPush.retryPush(AbstractPush.java:43) [BILIBILI-HELPER.jar:?]
	at top.misec.push.AbstractPush.doPush(AbstractPush.java:32) [BILIBILI-HELPER.jar:?]
	at top.misec.push.PushHelper.push(PushHelper.java:22) [BILIBILI-HELPER.jar:?]
	at top.misec.task.ServerPush.doServerPush(ServerPush.java:58) [BILIBILI-HELPER.jar:?]
	at top.misec.task.DailyTask.doDailyTask(DailyTask.java:78) [BILIBILI-HELPER.jar:?]
	at top.misec.BiliMain.main(BiliMain.java:65) [BILIBILI-HELPER.jar:?]

**Comment by SuperNG6** [comment]
更新2.0版，取消DEDEUSERID SESSDATA BILI_JCT环境变量，变更config.json填写
